/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.TirController;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import models.Sofer;

/**
 *
 * @author Stefan
 */
public class FrmAfisareDetaliiTir extends javax.swing.JDialog {

    private TirController tirController;
    
    /**
     * Creates new form FrmAfisareDetaliiTir
     */
    public FrmAfisareDetaliiTir(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JLabel getLblMarca() {
        return lblMarca;
    }

    public JLabel getLblModel() {
        return lblModel;
    }

    public JLabel getLblNrInmatriculare() {
        return lblNrInmatriculare;
    }

    public JLabel getLblStatus() {
        return lblStatus;
    }

    public JButton getBtnModService() {
        return btnModService;
    }

    public void setTirController(TirController tirController) {
        this.tirController = tirController;
    }

    public JList<Sofer> getLstSoferi() {
        return lstSoferi;
    }

    public JLabel getLblCnt() {
        return lblCnt;
    }

    public JLabel getLblPoze() {
        return lblPoze;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextMarca = new javax.swing.JLabel();
        lblTextModel = new javax.swing.JLabel();
        lblTextNrInmatriculare = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblNrInmatriculare = new javax.swing.JLabel();
        lblTextStatus = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPoze = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblCnt = new javax.swing.JLabel();
        btnModService = new javax.swing.JButton();
        lblTextSoferi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSoferi = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTextMarca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTextMarca.setText("Marca:");

        lblTextModel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTextModel.setText("Model:");

        lblTextNrInmatriculare.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTextNrInmatriculare.setText("Numar inmatriculare:");

        lblMarca.setText("jLabel1");

        lblModel.setText("jLabel2");

        lblNrInmatriculare.setText("jLabel3");

        lblTextStatus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTextStatus.setText("Status:");

        lblStatus.setText("jLabel1");

        lblPoze.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoze.setText("Poze");
        lblPoze.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btnPrevious.setText("<");
        btnPrevious.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblCnt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCnt.setText("0 / 0");

        btnModService.setText("Mod service");
        btnModService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModServiceActionPerformed(evt);
            }
        });

        lblTextSoferi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTextSoferi.setText("Soferi:");

        jScrollPane2.setViewportView(lstSoferi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTextMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMarca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTextModel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblModel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTextSoferi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextNrInmatriculare)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTextStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNrInmatriculare)
                            .addComponent(btnModService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCnt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext))
                    .addComponent(lblPoze, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPoze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext)
                            .addComponent(lblCnt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextMarca)
                            .addComponent(lblMarca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextModel)
                            .addComponent(lblModel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextNrInmatriculare)
                            .addComponent(lblNrInmatriculare))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextStatus)
                            .addComponent(lblStatus)
                            .addComponent(btnModService))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTextSoferi)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        tirController.previousImageDetalii();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        tirController.nextImageDetalii();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnModServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModServiceActionPerformed
        tirController.modService();
    }//GEN-LAST:event_btnModServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAfisareDetaliiTir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAfisareDetaliiTir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAfisareDetaliiTir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAfisareDetaliiTir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAfisareDetaliiTir dialog = new FrmAfisareDetaliiTir(new JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModService;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCnt;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblNrInmatriculare;
    private javax.swing.JLabel lblPoze;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTextMarca;
    private javax.swing.JLabel lblTextModel;
    private javax.swing.JLabel lblTextNrInmatriculare;
    private javax.swing.JLabel lblTextSoferi;
    private javax.swing.JLabel lblTextStatus;
    private javax.swing.JList<Sofer> lstSoferi;
    // End of variables declaration//GEN-END:variables
}
