/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.ApplicationController;
import controllers.SoferController;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import models.Sofer;
import models.Tir;
import renderers.CellRendererImage;

public class FrmAdministrare extends javax.swing.JFrame implements FrmAddSofer.OnSoferSaved, FrmAddTir.OnTirSaved {

    private ApplicationController applicationController = new ApplicationController();
    private SoferController soferController = new SoferController();

    public FrmAdministrare() {
        initComponents();
        tabelSoferi.getColumnModel().getColumn(4).setCellRenderer(new CellRendererImage());
//        tabelTiruri.getColumnModel().getColumn(4).setCellRenderer(new CellRendererImage());
    }

    public void setApplicationController(ApplicationController applicationController) {
        this.applicationController = applicationController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableModelSoferi1 = new tablemodels.TableModelSoferi();
        tabelModelTiruri1 = new tablemodels.TabelModelTiruri();
        panelPagini = new javax.swing.JTabbedPane();
        panelPaginaTabelTiruri = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAdaugaTiruri = new javax.swing.JButton();
        btnEditeazaTiruri = new javax.swing.JButton();
        btnStergeTiruri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTiruri = new javax.swing.JTable();
        panelPaginaTabelSoferi = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdaugaSoferi = new javax.swing.JButton();
        btnEditeazaSoferi = new javax.swing.JButton();
        btnStergeSoferi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelSoferi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrare");

        btnAdaugaTiruri.setText("Adauga");
        btnAdaugaTiruri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaTiruriActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdaugaTiruri);

        btnEditeazaTiruri.setText("Editeaza");
        btnEditeazaTiruri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditeazaTiruriActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditeazaTiruri);

        btnStergeTiruri.setText("Sterge");
        btnStergeTiruri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergeTiruriActionPerformed(evt);
            }
        });
        jPanel1.add(btnStergeTiruri);

        tabelTiruri.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabelTiruri.setModel(tabelModelTiruri1);
        jScrollPane1.setViewportView(tabelTiruri);

        javax.swing.GroupLayout panelPaginaTabelTiruriLayout = new javax.swing.GroupLayout(panelPaginaTabelTiruri);
        panelPaginaTabelTiruri.setLayout(panelPaginaTabelTiruriLayout);
        panelPaginaTabelTiruriLayout.setHorizontalGroup(
            panelPaginaTabelTiruriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaginaTabelTiruriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPaginaTabelTiruriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPaginaTabelTiruriLayout.setVerticalGroup(
            panelPaginaTabelTiruriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaginaTabelTiruriLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPagini.addTab("Administrare Tiruri", panelPaginaTabelTiruri);

        btnAdaugaSoferi.setText("Adauga");
        btnAdaugaSoferi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaSoferiActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdaugaSoferi);

        btnEditeazaSoferi.setText("Editeaza");
        btnEditeazaSoferi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditeazaSoferiActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditeazaSoferi);

        btnStergeSoferi.setText("Sterge");
        btnStergeSoferi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergeSoferiActionPerformed(evt);
            }
        });
        jPanel2.add(btnStergeSoferi);

        tabelSoferi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabelSoferi.setModel(tableModelSoferi1);
        jScrollPane2.setViewportView(tabelSoferi);
        if (tabelSoferi.getColumnModel().getColumnCount() > 0) {
            tabelSoferi.getColumnModel().getColumn(0).setHeaderValue("Nume si prenume");
            tabelSoferi.getColumnModel().getColumn(1).setHeaderValue("Poza");
        }

        javax.swing.GroupLayout panelPaginaTabelSoferiLayout = new javax.swing.GroupLayout(panelPaginaTabelSoferi);
        panelPaginaTabelSoferi.setLayout(panelPaginaTabelSoferiLayout);
        panelPaginaTabelSoferiLayout.setHorizontalGroup(
            panelPaginaTabelSoferiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaginaTabelSoferiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPaginaTabelSoferiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPaginaTabelSoferiLayout.setVerticalGroup(
            panelPaginaTabelSoferiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaginaTabelSoferiLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPagini.addTab("Tabel Date Soferi", panelPaginaTabelSoferi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPagini)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPagini)
        );

        panelPagini.getAccessibleContext().setAccessibleName("Administrare Tiruri");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdaugaTiruriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaTiruriActionPerformed
//        FrmAddTir f = new FrmAddTir(new javax.swing.JFrame(), true);
//        f.setOnTirSaved(this);
//        f.setVisible(true);
    }//GEN-LAST:event_btnAdaugaTiruriActionPerformed

    private void btnEditeazaTiruriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditeazaTiruriActionPerformed
        int index = tabelTiruri.convertRowIndexToModel(tabelTiruri.getSelectedRow());
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Va rog selectati un tir");
            return;
        }
//        FrmAddTir f = new FrmAddTir(new javax.swing.JFrame(), true, tabelModelTiruri1.getTirAtIndex(index));

//        for(File file : tabelModelTiruri1.getTirAtIndex(index).getPoze()) {
//            file.delete();
//        }
//        
//        tabelModelTiruri1.getTirAtIndex(index).getFolderPoze().delete();
//        f.setOnTirSaved(this);
//        f.setVisible(true);
    }//GEN-LAST:event_btnEditeazaTiruriActionPerformed

    private void btnStergeTiruriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergeTiruriActionPerformed
        int index = tabelTiruri.convertRowIndexToModel(tabelTiruri.getSelectedRow());
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Va rog sa selectati un tir");
            return;
        }
        int confirmValue = JOptionPane.showConfirmDialog(this, "Esti sigur ca vrei sa stergi linia?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirmValue == JOptionPane.YES_OPTION) {
//            for(File f : tabelModelTiruri1.getTirAtIndex(index).getPoze()) {
//                f.delete();
//            }
            tabelModelTiruri1.getListaTiruri().remove(index);
            tabelModelTiruri1.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnStergeTiruriActionPerformed

    private void btnAdaugaSoferiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaSoferiActionPerformed
//        FrmDateSofer f = new FrmDateSofer(new javax.swing.JFrame(), true);
//        f.setOnSoferSaved(this);
//        f.setVisible(true);
    }//GEN-LAST:event_btnAdaugaSoferiActionPerformed

    private void btnEditeazaSoferiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditeazaSoferiActionPerformed
        int index = tabelSoferi.convertRowIndexToModel(tabelSoferi.getSelectedRow());
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Va rog selectati un sofer!");
            return;
        }
//        tableModelSoferi1.getSoferAtIdex(index).getPoza().delete();
        FrmAddSofer f = new FrmAddSofer(new JDialog(), true, tableModelSoferi1.getSoferAtIdex(index));

        f.setOnSoferSaved(this);
        f.setVisible(true);
    }//GEN-LAST:event_btnEditeazaSoferiActionPerformed

    private void btnStergeSoferiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergeSoferiActionPerformed
        int index = tabelSoferi.convertRowIndexToModel(tabelSoferi.getSelectedRow());
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Va rog selectati un sofer!");
            return;
        }

        int confirmValue = JOptionPane.showConfirmDialog(this, "Esti sigur ca vrei sa stergi linia?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirmValue == JOptionPane.YES_OPTION) {
//            tableModelSoferi1.getSoferAtIdex(index).getPoza().delete();
            tableModelSoferi1.getListaSoferi().remove(index);
            tableModelSoferi1.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnStergeSoferiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdaugaSoferi;
    private javax.swing.JButton btnAdaugaTiruri;
    private javax.swing.JButton btnEditeazaSoferi;
    private javax.swing.JButton btnEditeazaTiruri;
    private javax.swing.JButton btnStergeSoferi;
    private javax.swing.JButton btnStergeTiruri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelPaginaTabelSoferi;
    private javax.swing.JPanel panelPaginaTabelTiruri;
    private javax.swing.JTabbedPane panelPagini;
    private tablemodels.TabelModelTiruri tabelModelTiruri1;
    private javax.swing.JTable tabelSoferi;
    private javax.swing.JTable tabelTiruri;
    private tablemodels.TableModelSoferi tableModelSoferi1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void saveSofer(Sofer sofer) {
        System.out.println(sofer);
        tableModelSoferi1.addSofer(sofer);
    }

    @Override
    public void saveTir(Tir tir) {
        tabelModelTiruri1.addTir(tir);
        System.out.println(tir);
    }
}
