/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.toedter.calendar.JDateChooser;
import controllers.RapoarteController;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Session;
import org.hibernate.internal.SessionImpl;
import utils.HibernateUtil;


/**
 *
 * @author Stefan
 */
public class FrmRaport extends javax.swing.JDialog {

    private RapoarteController rapoarteController;

    public FrmRaport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Calendar c = Calendar.getInstance();
        //dateChooserDataSfarsit.setMaxSelectableDate(c.getTime());
        // dateChooserDataInceput.setMaxSelectableDate(c.getTime());
        chooserDataFinal.setDate(c.getTime());
        c.add(Calendar.DAY_OF_MONTH, -30);
        chooserDataInceput.setDate(c.getTime());
    }

    public JPanel getPanelCustom() {
        return panelCustom;
    }

    public JComboBox<String> getCmbRapoarte() {
        return cmbRapoarte;
    }

    public void setRapoarteController(RapoarteController rapoarteController) {
        this.rapoarteController = rapoarteController;
    }

    public JDateChooser getChooserDataFinal() {
        return chooserDataFinal;
    }

    public JDateChooser getChooserDataInceput() {
        return chooserDataInceput;
    }

    public JList<String> getLstSoferi() {
        return lstSoferi;
    }

    public JList<String> getLstTiruri() {
        return jList2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbRapoarte = new javax.swing.JComboBox<>();
        lblTipRaport = new javax.swing.JLabel();
        lblDataInceput = new javax.swing.JLabel();
        lblDataSfarsit = new javax.swing.JLabel();
        chooserDataInceput = new com.toedter.calendar.JDateChooser();
        chooserDataFinal = new com.toedter.calendar.JDateChooser();
        btnGenereaza = new javax.swing.JButton();
        panelCustom = new javax.swing.JPanel();
        lblSoferi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSoferi = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        lblTiruri = new javax.swing.JLabel();
        btnSelecteazaSoferi = new javax.swing.JButton();
        btnDeselecteazaSoferi = new javax.swing.JButton();
        btnDeselecteazaTiruri = new javax.swing.JButton();
        btnSelecteazaTiruri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbRapoarte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRapoarteItemStateChanged(evt);
            }
        });

        lblTipRaport.setText("Tipul raportului:");

        lblDataInceput.setText("Data inceput:");

        lblDataSfarsit.setText("Data sfarsit:");

        chooserDataInceput.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chooserDataInceputPropertyChange(evt);
            }
        });

        btnGenereaza.setText("Genereaza raport");
        btnGenereaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenereazaActionPerformed(evt);
            }
        });

        lblSoferi.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblSoferi.setText("Soferi:");

        jScrollPane1.setViewportView(lstSoferi);

        jScrollPane2.setViewportView(jList2);

        lblTiruri.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblTiruri.setText("Tiruri:");

        btnSelecteazaSoferi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSelecteazaSoferi.setText("<html><center>Selecteaza<br/>tot</center></html>");
        btnSelecteazaSoferi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnDeselecteazaSoferi.setText("<html><center>Stergere<br/>selectie</center></html>");

        btnDeselecteazaTiruri.setText("<html><center>Stergere<br/>selectie</center></html>");

        btnSelecteazaTiruri.setText("<html><center>Selecteaza<br/>tot</center></html>");

        javax.swing.GroupLayout panelCustomLayout = new javax.swing.GroupLayout(panelCustom);
        panelCustom.setLayout(panelCustomLayout);
        panelCustomLayout.setHorizontalGroup(
            panelCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomLayout.createSequentialGroup()
                        .addGroup(panelCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoferi))
                        .addGap(18, 18, 18)
                        .addGroup(panelCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTiruri)))
                    .addGroup(panelCustomLayout.createSequentialGroup()
                        .addComponent(btnSelecteazaSoferi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeselecteazaSoferi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelecteazaTiruri, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeselecteazaTiruri, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelCustomLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeselecteazaSoferi, btnSelecteazaSoferi, btnSelecteazaTiruri});

        panelCustomLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        panelCustomLayout.setVerticalGroup(
            panelCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoferi)
                    .addComponent(lblTiruri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeselecteazaSoferi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecteazaSoferi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeselecteazaTiruri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecteazaTiruri, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipRaport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbRapoarte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDataInceput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooserDataInceput, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDataSfarsit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooserDataFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnGenereaza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCustom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipRaport, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRapoarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataSfarsit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataInceput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooserDataInceput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooserDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenereaza)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenereazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenereazaActionPerformed
        rapoarteController.doWork();
    }//GEN-LAST:event_btnGenereazaActionPerformed


    private void chooserDataInceputPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chooserDataInceputPropertyChange
        if (chooserDataInceput.getDate() != null) {
            Calendar c = Calendar.getInstance();
            c.setTime(chooserDataInceput.getDate());
            chooserDataFinal.setMinSelectableDate(c.getTime());
        }

    }//GEN-LAST:event_chooserDataInceputPropertyChange

    private void cmbRapoarteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRapoarteItemStateChanged
        rapoarteController.itemChanged();
    }//GEN-LAST:event_cmbRapoarteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRaport dialog = new FrmRaport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeselecteazaSoferi;
    private javax.swing.JButton btnDeselecteazaTiruri;
    private javax.swing.JButton btnGenereaza;
    private javax.swing.JButton btnSelecteazaSoferi;
    private javax.swing.JButton btnSelecteazaTiruri;
    private com.toedter.calendar.JDateChooser chooserDataFinal;
    private com.toedter.calendar.JDateChooser chooserDataInceput;
    private javax.swing.JComboBox<String> cmbRapoarte;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDataInceput;
    private javax.swing.JLabel lblDataSfarsit;
    private javax.swing.JLabel lblSoferi;
    private javax.swing.JLabel lblTipRaport;
    private javax.swing.JLabel lblTiruri;
    private javax.swing.JList<String> lstSoferi;
    private javax.swing.JPanel panelCustom;
    // End of variables declaration//GEN-END:variables
}
