DROP TABLE SOFERI;
CREATE TABLE SOFERI
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NUME VARCHAR(100) NOT NULL,
PRENUME VARCHAR(100) NOT NULL,
CNP VARCHAR(13) NOT NULL,
IMAGEPATH VARCHAR(100) NOT NULL
);


ALTER TABLE SOFERI ADD PRIMARY KEY(ID);
ALTER TABLE SOFERI ADD UNIQUE(CNP);


DROP TABLE TIRURI;
CREATE TABLE TIRURI
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
MODEL INTEGER NOR NULL,
NR_INMATRICULARE VARCHAR(7) NOT NULL,
STARE INTEGER NOT NULL
);

ALTER TABLE TIRURI ADD PRIMARY KEY(ID);
ALTER TABLE TIRURI ADD UNIQUE(NR_INMATRICULARE);

DROP TABLE MODELE
CREATE TABLE MODELE
(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NUME VARCHAR(100) NOT NULL,
    MARCA INTEGER NOT NULL,
    ACTIV BOOLEAN NOT NULL,
);

ALTER TABLE MODELE
ADD PRIMARY KEY(ID);
ALTER TABLE MODELE ADD UNIQUE NUME;
ALTER TABLE MODELE ADD FOREIGN KEY(MARCA) REFERENCES MARCA(ID);

DROP TABLE POZE;
CREATE TABLE POZE
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TIP_OBIECT INTEGER NOT NULL,
ID_OBIECT INTEGER NOT NULL,
IMAGEPATH VARCHAR(100) NOT NULL
);

ALTER TABLE POZE ADD PRIMARY KEY(ID);
ALTER TABLE POZE ADD UNIQUE(IMAGEPATH);

DROP TABLE MARCA;
CREATE TABLE MARCA
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NUME VARCHAR(100) NOT NULL,
ACTIVA INTEGER NOT NULL
);

ALTER TABLE MARCA ADD PRIMARY KEY(ID);
ALTER TABLE MARCA ADD UNIQUE(NUME);

DROP TABLE SOFERI_TIRURI;
CREATE TABLE SOFERI_TIRURI
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
SOFER INTEGER NOT NULL,
TIR INTEGER NOT NULL
);

ALTER TABLE SOFERI_TIRURI ADD PRIMARY KEY(ID);

DROP TABLE INREGISTRARI;
CREATE TABLE INREGISTRARI
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
SOFERI_TIRURI INTEGER NOT NULL,
DATA_SOSIRE DATE NOT NULL,
DATA_PLECARE DATE
);

ALTER TABLE INREGISTRARI ADD PRIMARY KEY(ID);

DROP TABLE STARI;
CREATE TABLE STARI
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NUME VARCHAR(100) NOT NULL,
VALID INTEGER NOT NULL
);



ALTER TABLE STARI ADD PRIMARY KEY(ID);
ALTER TABLE STARI ADD UNIQUE(NUME);

ALTER TABLE TIRURI
ADD FOREIGN KEY(MARCA)
REFERENCES MARCA(ID);

ALTER TABLE TIRURI
ADD FOREIGN KEY(STARE)
REFERENCES STARI(ID);

ALTER TABLE SOFERI_TIRURI
ADD FOREIGN KEY(SOFER)
REFERENCES SOFERI(ID);

ALTER TABLE SOFERI_TIRURI
ADD FOREIGN KEY(TIR)
REFERENCES TIRURI(ID);

ALTER TABLE INREGISTRARI
ADD FOREIGN KEY(SOFERI_TIRURI)
REFERENCES SOFERI_TIRURI(ID);

ALTER TABLE SOFERI_TIRURI
DROP CONSTRAINT SQL220630181730330

DROP TABLE UTILIZATORI;
CREATE TABLE UTILIZATORI
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NUME VARCHAR(100) NOT NULL,
PRENUME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PAROLA VARCHAR(100) NOT NULL,
VALID BOOLEAN NOT NULL
);

DROP TABLE ROLURI;
CREATE TABLE ROLURI
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NUME VARCHAR(100) NOT NULL,
VALID BOOLEAN NOT NULL
);

DROP TABLE UTILIZATORI_ROLURI;
CREATE TABLE UTILIZATORI_ROLURI
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
UTILIZATOR INTEGER NOT NULL,
ROL INTEGER NOT NULL,
DATA_INCEPUT DATE NOT NULL,
DATA_SFARSIT DATE
);

ALTER TABLE UTILIZATORI ADD PRIMARY KEY(ID);
ALTER TABLE ROLURI ADD PRIMARY KEY(ID);
ALTER TABLE UTILIZATORI_ROLURI ADD PRIMARY KEY(ID);

ALTER TABLE UTILIZATORI_ROLURI
ADD FOREIGN KEY(UTILIZATOR)
REFERENCES UTILIZATORI(ID);

ALTER TABLE UTILIZATORI_ROLURI
ADD FOREIGN KEY(ROL)
REFERENCES ROLURI(ID);
