package models;
// Generated May 12, 2022 5:57:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inregistrari generated by hbm2java
 */
public class Inregistrare  implements java.io.Serializable {


     private int id;
     private int idSoferiTiruri;
     private Date dataSosire;
     private Date dataPlecare;
     private SoferiTiruri soferTir;

    public Inregistrare() {
    }

    public Inregistrare(int id, int idSoferiTiruri, Date dataSosire, Date dataPlecare) {
       this.id = id;
       this.idSoferiTiruri = idSoferiTiruri;
       this.dataSosire = dataSosire;
       this.dataPlecare = dataPlecare;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdSoferiTiruri() {
        return idSoferiTiruri;
    }

    public void setIdSoferiTiruri(int idSoferiTiruri) {
        this.idSoferiTiruri = idSoferiTiruri;
    }

    public Date getDataSosire() {
        return dataSosire;
    }

    public void setDataSosire(Date dataSosire) {
        this.dataSosire = dataSosire;
    }

    public Date getDataPlecare() {
        return dataPlecare;
    }

    public void setDataPlecare(Date dataPlecare) {
        this.dataPlecare = dataPlecare;
    }

    public SoferiTiruri getSoferTir() {
        return soferTir;
    }

    public void setSoferTir(SoferiTiruri soferTir) {
        this.soferTir = soferTir;
        if (soferTir!=null){
            this.idSoferiTiruri = soferTir.getId();
        }
    }
   
    

}


