package models;
// Generated May 12, 2022 5:57:09 PM by Hibernate Tools 4.3.1

import java.io.File;
import java.util.HashSet;
import java.util.Set;




/**
 * Soferi generated by hbm2java
 */
public class Sofer  implements java.io.Serializable {


     private int id;
     private String nume;
     private String prenume;
     private String cnp;
     private String imagepath;
     private Set<SoferiTiruri> soferiTiruri = new HashSet<SoferiTiruri>(0);

    public Sofer() {
    }

    public Sofer(int id, String nume, String prenume, String cnp, String imagepath) {
       this.id = id;
       this.nume = nume;
       this.prenume = prenume;
       this.cnp = cnp;
       this.imagepath = imagepath;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public String getPrenume() {
        return this.prenume;
    }
    
    public void setPrenume(String prenume) {
        this.prenume = prenume;
    }
    public String getCnp() {
        return this.cnp;
    }
    
    public void setCnp(String cnp) {
        this.cnp = cnp;
    }
    public String getImagepath() {
        return this.imagepath;
    }
    
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath;
    }

    public Set<SoferiTiruri> getSoferiTiruri() {
        return soferiTiruri;
    }

    public void setSoferiTiruri(Set<SoferiTiruri> soferiTiruri) {
        this.soferiTiruri = soferiTiruri;
    }
    

    public File getPoza(){
        File currentDirectory=new File(".");
        if(this.getImagepath()!=null){
            return new File(currentDirectory,String.format("/poze/soferi/%s",this.getImagepath()));
        }
       return new File(currentDirectory,String.format("/poze/no-image-icon.png"));
    }
    
    public void setPoza(File poza){
        this.imagepath=String.format("%s", poza.getName());
    }
    
    public String getNumeComplet(){
        return String.format("%s %s", this.nume, this.prenume);
    }

    @Override
    public String toString() {
        return "Sofer{" + "id=" + id + ", nume=" + nume + ", prenume=" + prenume + ", cnp=" + cnp + ", imagepath=" + imagepath + '}';
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Sofer other = (Sofer) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    
    
}


