package models;
// Generated Jun 2, 2022 6:30:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SoferiTiruri generated by hbm2java
 */
public class SoferiTiruri  implements java.io.Serializable {


     private int id;
     private int idSofer;
     private int idTir;
     private Sofer sofer;
     private Tir tir;
     private boolean valid;
     private Set inregistrari = new HashSet(0);
     private boolean inCursa;
     private Date dataInceput;
     private Date dataSfarsit;

    public SoferiTiruri() {
    }

	
    public SoferiTiruri(int idSofer, int idTir, Sofer sofer, Tir tir) {
        this.idSofer = idSofer;
        this.idTir = idTir;
        this.sofer = sofer;
        this.tir = tir;
    }
    public SoferiTiruri(int idSofer, int idTir, Sofer sofer, Tir tir, Set inregistrari) {
       this.idSofer = idSofer;
       this.idTir = idTir;
       this.sofer = sofer;
       this.tir = tir;
       this.inregistrari = inregistrari;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdSofer() {
        return this.idSofer;
    }
    
    public void setIdSofer(int idSofer) {
        this.idSofer = idSofer;
    }
    public int getIdTir() {
        return this.idTir;
    }
    
    public void setIdTir(int idTir) {
        this.idTir = idTir;
    }
    public Sofer getSofer() {
        return this.sofer;
    }
    
    public void setSofer(Sofer sofer) {
        this.sofer = sofer;
    }
    public Tir getTir() {
        return this.tir;
    }
    
    public void setTir(Tir tir) {
        this.tir = tir;
    }
    public Set getInregistrari() {
        return this.inregistrari;
    }
    
    public void setInregistrari(Set inregistrari) {
        this.inregistrari = inregistrari;
    }

    public boolean isValid() {
        return valid;
    }

    public void setValid(boolean valid) {
        this.valid = valid;
    }

    public void setInCursa(boolean inCursa) {
        this.inCursa = inCursa;
    }

    public boolean isInCursa() {
        return inCursa;
    }

    public void setDataInceput(Date dataInceput) {
        this.dataInceput = dataInceput;
    }

    public void setDataSfarsit(Date dataSfarsit) {
        this.dataSfarsit = dataSfarsit;
    }

    public Date getDataInceput() {
        return dataInceput;
    }

    public Date getDataSfarsit() {
        return dataSfarsit;
    }
    
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SoferiTiruri other = (SoferiTiruri) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    
}


