package models;
// Generated Jun 2, 2022 6:30:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stare generated by hbm2java
 */
public class Stare  implements java.io.Serializable {


     private int id;
     private String nume;
     private int valid;
     private Set tiruri = new HashSet(0);

    public Stare() {
    }

	
    public Stare(int id,String nume, int valid) {
        this.id = id;
        this.nume = nume;
        this.valid = valid;
    }
    public Stare(String nume, int valid, Set tiruri) {
       this.nume = nume;
       this.valid = valid;
       this.tiruri = tiruri;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public int getValid() {
        return this.valid;
    }
    
    public void setValid(int valid) {
        this.valid = valid;
    }
    public Set getTiruri() {
        return this.tiruri;
    }
    
    public void setTiruri(Set tiruri) {
        this.tiruri = tiruri;
    }




}


