package models;
// Generated May 12, 2022 5:57:09 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Stari generated by hbm2java
 */
public class Stare  implements java.io.Serializable {


     private int id;
     private String nume;
     private int valid;
     private Set<Tir> tiruri = new HashSet<Tir>(0);

    public Stare() {
    }

    public Stare(int id, String nume, int valid) {
       this.id = id;
       this.nume = nume;
       this.valid = valid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public int getValid() {
        return this.valid;
    }
    
    public void setValid(int valid) {
        this.valid = valid;
    }

    public void setTiruri(Set<Tir> tiruri) {
        this.tiruri = tiruri;
    }

    public Set<Tir> getTiruri() {
        return tiruri;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Stare other = (Stare) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }




}


